### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by sschadwick** [UWFosterIT/node-gws#13]
```javascript
{ data: {},
  error: true,
  statusCode: 400,
  message: [ 'sax invalid xml' ] }
```

```
  Initializing the module with bad config info
    ✓ should error when given missing cert or key

  Initializing the module with dummy certs
    ✓ should not error

  Group
    1) should create a group

  2 passing (250ms)
  1 failing

  1) Group
       should create a group:

      AssertionError: expected 400 to equal 201
      + expected - actual

      -400
      +201

      at Context.it (test/unit/group-test.js:39:34)
      at <anonymous>
      at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

```javascript
// config.js
module.exports = {
  baseUrl:   'https://iam-ws.u.washington.edu:7443/group_sws/v2/',
  cacheExt:  '.json',
  cacheMode: 'wild',
  cachePath: '/Users/schad/Projects/node-gws/cache/',
  certInfo: {
    // file: {
    //   cert: '/Users/schad/.ssh/laps_cert.cer',
    //   key:  '/Users/schad/.ssh/laps_cert.key'
    // },
    s3: {
      certBucket: 'uwfosterit.certs',
      certKey:    'laps_cert.cer',
      keyBucket:  'uwfosterit.certs',
      keyKey:     'laps_cert.key'
    }
  },
  logLevel: 'info'
};
```

Neither `file` nor `s3` config props change the error.

**Comment by kevintechie** [comment]
Can you re-confirm tests are failing. I just re-ran them and none are failing.

**Comment by sschadwick** [comment]
Yes. Failing with same error in node-gws and when consumed via cohort-api.

**Comment by kevintechie** [comment]
Using old v2 API endpoint. Worked when switched to v3 API.

Updating sample config to include the v3 API endpoint.
